const api=window.buildy.api('gamerecarga-mz');
const A=window.buildy.assets.getUrl;
const products=[
{id:'cod',game:'Call of Duty Mobile',image:A('cod-mobile.jpg'),items:[['80 CP',80],['420 CP',390],['880 CP',760],['2400 CP',1890]]},
{id:'ff',game:'Free Fire',image:A('freefire.jpg'),items:[['100 Diamantes',85],['310 Diamantes',245],['520 Diamantes',395],['1060 Diamantes',790]]},
{id:'ml',game:'Mobile Legends',image:A('mobile-legends.jpg'),items:[['86 Diamonds',75],['172 Diamonds',145],['257 Diamonds',210],['706 Diamonds',520]]},
{id:'pubg',game:'PUBG Mobile',image:A('pubg.jpg'),items:[['60 UC',75],['325 UC',365],['660 UC',690],['1800 UC',1790]]},
{id:'roblox',game:'Roblox',image:A('roblox.jpg'),items:[['80 Robux',85],['400 Robux',390],['800 Robux',720],['1700 Robux',1450]]},
{id:'fc-mobile',game:'EA FC Mobile',image:A('ea-fc-mobile.jpg'),items:[['100 FC Points',95],['520 FC Points',450],['1050 FC Points',850],['2200 FC Points',1690]]}
];
const money=n=>new Intl.NumberFormat('pt-MZ').format(n)+' MT';
const root=document.querySelector('#app');
function storefront(){
root.innerHTML=`<div class="site"><header class="nav"><div class="brand"><div class="brandMark">⌁</div><div><strong>GAME<span>RECARGA</span> MZ</strong><small>RECARGA O TEU JOGO. JOGA SEM PARAR!</small></div></div><nav><a class="active" href="#inicio">⌂ <span>Início</span></a><a href="#como">Como funciona</a><button id="orders" class="navBtn">Meus pedidos</button><a href="#suporte">Suporte</a><a href="#contacto">Contacto</a></nav><div class="navRight">${window.buildy.user?'<button id="admin" class="login">◉ Entrar</button>':'<button class="login">◉ Entrar</button>'}<button class="cart">🛒 <b>0 MT</b></button></div></header>
<section id="inicio" class="hero"><div class="heroArt"><div class="heroGames">${products.map(p=>`<img src="${p.image}" alt="${p.game}">`).join('')}</div><div class="heroShade"></div><div class="heroCopy"><span class="eyebrow">RECARGAS DIGITAIS · MOÇAMBIQUE</span><h1>RECARGA O TEU JOGO.<br><span>JOGA SEM PARAR!</span></h1><p>Compra Diamantes, UC, CP, Robux e outros créditos de jogos com pagamento local.</p><a href="#loja" class="heroCta">ESCOLHE O TEU JOGO <b>→</b></a></div></div></section>
<section id="loja" class="catalog"><div class="sectionTitle"><div><span class="eyebrow">CATÁLOGO</span><h2>ESCOLHE O TEU <span>JOGO</span></h2><p>Seleciona o jogo e o pacote que desejas comprar.</p></div><input id="search" class="search" placeholder="Pesquisar jogo..."></div><div id="grid" class="grid"></div></section>
<section id="como" class="benefits"><div><b>◈</b><strong>Pagamento 100% Seguro</strong><small>Processado pela NetShop</small></div><div><b>ϟ</b><strong>Entrega Rápida</strong><small>Recargas após confirmação</small></div><div id="suporte"><b>◉</b><strong>Suporte 24/7</strong><small>Estamos sempre disponíveis</small></div><div><b>★</b><strong>Melhores Preços</strong><small>Ofertas todos os dias</small></div></section>
<footer id="contacto"><div><strong>GAMERECARGA MZ</strong><span>Recargas digitais para gamers em Moçambique.</span></div><div>© 2026 GameRecarga MZ. Todos os direitos reservados.</div><div class="social">f&nbsp;&nbsp;◎&nbsp;&nbsp;◉</div></footer></div>`;
draw(products);document.querySelector('#search').oninput=e=>draw(products.filter(p=>p.game.toLowerCase().includes(e.target.value.toLowerCase())));document.querySelector('#orders').onclick=orders;if(window.buildy.user&&document.querySelector('#admin'))document.querySelector('#admin').onclick=admin;
}
function draw(list){document.querySelector('#grid').innerHTML=list.map((p,pi)=>`<article class="game"><div class="gameImage"><img src="${p.image}" alt="${p.game}"><span>TOP UP</span></div><div class="gameBody"><h3>${p.game}</h3><div class="packs">${p.items.map((x,i)=>`<button class="pack" data-p="${pi}" data-i="${i}"><span>◆ ${x[0]}</span><b>${money(x[1])}</b></button>`).join('')}</div><button class="buy" data-p="${pi}" data-i="0">Comprar</button></div></article>`).join('');document.querySelectorAll('.pack,.buy').forEach(b=>b.onclick=()=>checkout(products[b.dataset.p],Number(b.dataset.i||0)))}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="sheet"><button class="close">×</button>${html}</div></div>`);document.querySelector('.close').onclick=()=>document.querySelector('.modal').remove()}
function checkout(p,i){const x=p.items[i];modal(`<span class="eyebrow">CHECKOUT</span><h2>${p.game}</h2><div class="selected"><span>${x[0]}</span><b>${money(x[1])}</b></div><label>ID do jogador<input id="pid" placeholder="Ex.: 123456789"></label><label>Número de pagamento<input id="phone" placeholder="84 123 4567"></label><label>Método de pagamento<select id="pay"><option value="mpesa">M-Pesa</option><option value="mkesh">mKesh</option><option value="bim">Visa / Mastercard · BIM</option><option value="bci">Visa / Mastercard · BCI</option></select></label><button id="go" class="heroCta full">Continuar para pagamento · ${money(x[1])}</button><p class="note">O pagamento será processado de forma segura pela NetShop.</p>`);document.querySelector('#go').onclick=async()=>{const pid=document.querySelector('#pid').value.trim(),phone=document.querySelector('#phone').value.trim(),method=document.querySelector('#pay').value;if(!pid)return alert('Preencha o ID do jogador.');if((method==='mpesa'||method==='mkesh')&&!phone)return alert('Preencha o número de pagamento.');try{const r=await api.createOrder({game:p.game,pack:x[0],amount:x[1],playerId:pid,contact:phone||'card',payment:method});document.querySelector('.modal').remove();if(r.checkoutUrl)window.location.href=r.checkoutUrl;else modal(`<div class="success"><div class="check">✓</div><span class="eyebrow">PEDIDO CRIADO</span><h2>${r.id}</h2><p>Referência de pagamento: <b>${r.paymentReference||'pendente'}</b></p><button id="refresh" class="heroCta full">Ver estado do pagamento</button></div>`);if(document.querySelector('#refresh'))document.querySelector('#refresh').onclick=async()=>{const o=await api.checkPayment({id:r.id});alert(o.status)}}catch(e){alert(e.message||'Falha no pagamento')}}}
async function orders(){const os=await api.listOrders({});modal(`<span class="eyebrow">PEDIDOS</span><h2>Meus pedidos</h2><div class="orders">${os.length?os.slice(0,30).map(o=>`<div class="order"><div><b>${o.game}</b><span>${o.pack} · ${o.payment||''}</span><small>${o.id}</small></div><strong>${money(o.amount)}</strong><em>${o.status}</em></div>`).join(''):'<p>Sem pedidos.</p>'}</div>`)}
async function admin(){const[d,os]=await Promise.all([api.dashboard({}),api.listOrders({})]);modal(`<span class="eyebrow">ADMINISTRAÇÃO</span><h2>Painel da loja</h2><div class="stats"><div><small>Pedidos</small><b>${d.orders}</b></div><div><small>Pagos</small><b>${d.paid}</b></div><div><small>Receita</small><b>${money(d.revenue)}</b></div><div><small>Pendentes</small><b>${d.pending}</b></div></div><div class="orders">${os.slice(0,12).map(o=>`<div class="order"><div><b>${o.game}</b><span>${o.playerId||''}</span><small>${o.id}</small></div><strong>${money(o.amount)}</strong><em>${o.status}</em></div>`).join('')}</div>`)}
storefront();
