export const manifest={id:'gamerecarga-mz',version:'4.0.0',manifestVersion:'2026-05-28',capabilities:{imports:['buildy:storage/kv@1.0','buildy:network/fetch@1.0','buildy:secrets/fetch@1.0','buildy:storage/blob@1.0'],fetchHosts:['www.netshop.co.mz','netshop.co.mz']}};
const NETSHOP='https://www.netshop.co.mz/api/v1';
const get=(env,k)=>env.storage.get(k); const put=(env,k,v)=>env.storage.put(k,v);
const rid=()=>`GMZ-${Date.now().toString(36).toUpperCase()}-${Math.floor(Math.random()*900+100)}`;
const uuid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const order=async(env,id)=>get(env,'order:'+id); const save=async(env,o)=>put(env,'order:'+o.id,o);
const WALLET_IDS={mpesa:'574418',mkesh:'247460',bim:'767755',bci:'111895'};
async function ns(env,path,options={}){return env.fetch(NETSHOP+path,{...options,headers:{Accept:'application/json','Content-Type':'application/json',Authorization:'Bearer {{secret:NETSHOP_API_KEY}}','X-API-Version':'2024-10-12','X-Wallet-ID':options.walletId||WALLET_IDS.mpesa,'Idempotency-Key':options.idempotencyKey||uuid(),...(options.headers||{})}})}
export const routes=[
{op:'createOrder',method:'POST',description:'Create a GameRecarga order and a NetShop charge.',input:{type:'object'},output:{type:'object'},handler:async(input,{env})=>{const amount=Number(input.amount);if(!amount||amount<1||amount>50000)throw new Error('Valor inválido');if(!input.game||!input.pack||!input.playerId||!input.contact)throw new Error('Dados do pedido incompletos');const method=String(input.payment||'mpesa').toLowerCase();const methodMap={mpesa:'mpesa',mkesh:'mkesh',bim:'card',bci:'card',card:'card',visa:'card',mastercard:'card'};const netMethod=methodMap[method];if(!netMethod)throw new Error('Método de pagamento não suportado');const walletId=method==='mpesa'?WALLET_IDS.mpesa:method==='mkesh'?WALLET_IDS.mkesh:method==='bci'?WALLET_IDS.bci:WALLET_IDS.bim;const id=rid();const o={id,game:String(input.game),pack:String(input.pack),amount,currency:'MZN',playerId:String(input.playerId),contact:String(input.contact),payment:netMethod,status:'Pagamento pendente',paymentStatus:'pending',deliveryStatus:'waiting_payment',createdAt:new Date().toISOString()};await save(env,o);const rawContact=String(input.contact).replace(/\D/g,'');const msisdn=(netMethod==='mpesa'||netMethod==='mkesh')?(rawContact.startsWith('258')?'+'+rawContact:rawContact.startsWith('0')?'+258'+rawContact.slice(1):'+258'+rawContact):undefined;const payload={amount,currency:'MZN',method:netMethod,msisdn,reference:id,description:`${o.game} - ${o.pack}`.slice(0,180)};const r=await ns(env,'/charges',{method:'POST',body:JSON.stringify(payload),idempotencyKey:id,walletId});const raw=await r.text();let d={};try{d=JSON.parse(raw)}catch{}if(!r.ok){o.status='Pagamento falhou';o.paymentStatus='error';o.error=d?.message||d?.error?.message||d?.error||raw||`NetShop HTTP ${r.status}`;await save(env,o);const ids=(await get(env,'orders'))||[];if(!ids.includes(id)){ids.unshift(id);await put(env,'orders',ids.slice(0,500))}throw new Error(`NetShop HTTP ${r.status}: ${o.error}`)}const c=d?.data||d;o.paymentId=c.id||c.charge_id||null;o.paymentReference=c.reference||c.payment_reference||id;o.checkoutUrl=c.checkout_url||c.payment_url||c.checkoutUrl||null;o.paymentStatus=String(c.status||'pending').toLowerCase();if(['succeeded','successful','paid','completed'].includes(o.paymentStatus)){o.status='Pagamento confirmado';o.deliveryStatus='ready_for_delivery';o.paidAt=new Date().toISOString()}await save(env,o);const ids=(await get(env,'orders'))||[];ids.unshift(id);await put(env,'orders',ids.slice(0,500));return{id,status:o.status,paymentStatus:o.paymentStatus,paymentReference:o.paymentReference,checkoutUrl:o.checkoutUrl,chargeId:o.paymentId}}},
{op:'listOrders',method:'GET',description:'List recent GameRecarga orders.',readOnly:true,input:{type:'object'},output:{type:'array'},handler:async(_,{env})=>{const ids=(await get(env,'orders'))||[];const out=[];for(const id of ids.slice(0,100)){const o=await order(env,id);if(o)out.push(o)}return out}},
{op:'getOrder',method:'GET',description:'Get one order by id.',readOnly:true,input:{type:'object'},output:{type:'object'},handler:async(input,{env})=>{const o=await order(env,input.id);if(!o)throw new Error('Pedido não encontrado');return o}},
{op:'checkPayment',method:'GET',description:'Read the locally stored payment status; NetShop status is updated by webhook.',readOnly:true,input:{type:'object'},output:{type:'object'},handler:async(input,{env})=>{const o=await order(env,input.id);if(!o)throw new Error('Pedido não encontrado');return o}},
{op:'webhook',method:'POST',description:'Receive NetShop payment events and update the matching GameRecarga order.',input:{type:'object'},output:{type:'object'},handler:async(input,{env})=>{const body=input||{};const data=body.data||body.charge||body.payment||body;const reference=data.reference||data.payment_reference||data.charge?.reference||data.payment?.reference;const chargeId=data.id||data.charge_id||data.charge?.id;if(!reference&&!chargeId)return{received:true,matched:false};const ids=(await get(env,'orders'))||[];let found=null;for(const id of ids.slice(0,500)){const o=await order(env,id);if(o&&(o.paymentReference===reference||o.paymentId===chargeId)){found=o;break}}if(!found)return{received:true,matched:false};const status=String(data.status||data.charge?.status||data.payment?.status||body.event||'').toLowerCase();found.paymentStatus=status;found.updatedAt=new Date().toISOString();if(status.includes('succeed')||status==='successful'||status==='paid'||status==='completed'||status==='payment.succeeded'){found.status='Pagamento confirmado';found.deliveryStatus='ready_for_delivery';found.paidAt=new Date().toISOString()}else if(status.includes('fail')||status.includes('cancel')||status==='payment.failed'){found.status='Pagamento falhou';found.deliveryStatus='cancelled'}else if(status.includes('pending')||status==='processing'){found.status='Pagamento pendente'}await save(env,found);return{received:true,matched:true,orderId:found.id,status:found.status}}},
{op:'saveProduct',method:'POST',description:'Create or update a catalog product.',input:{type:'object'},output:{type:'object'},handler:async(input,{env})=>{const p={...input,updatedAt:new Date().toISOString()};if(!p.id)p.id='p-'+Date.now().toString(36);await put(env,'product:'+p.id,p);const ids=(await get(env,'products'))||[];if(!ids.includes(p.id))ids.push(p.id);await put(env,'products',ids);return p}},
{op:'listProducts',method:'GET',description:'List catalog products.',readOnly:true,input:{type:'object'},output:{type:'array'},handler:async(_,{env})=>{const ids=(await get(env,'products'))||[];const out=[];for(const id of ids){const p=await get(env,'product:'+id);if(p)out.push(p)}return out}},
{op:'dashboard',method:'GET',description:'Return GameRecarga sales metrics.',readOnly:true,input:{type:'object'},output:{type:'object'},handler:async(_,{env})=>{const ids=(await get(env,'orders'))||[];const os=[];for(const id of ids.slice(0,500)){const o=await order(env,id);if(o)os.push(o)}const paid=os.filter(o=>o.status==='Pagamento confirmado'||['successful','succeeded','paid','completed'].includes(o.paymentStatus));return{orders:os.length,paid:paid.length,revenue:paid.reduce((s,o)=>s+Number(o.amount||0),0),pending:os.filter(o=>o.status==='Pagamento pendente').length,failed:os.filter(o=>o.status==='Pagamento falhou').length}}}
];
export default {fetch:()=>new Response('GameRecarga MZ backend')};
