const NETSHOP_BASE='https://www.netshop.co.mz/api/v1';
const WALLET_IDS={mpesa:'574418',mkesh:'247460',bim:'767755',bci:'111895'};

function corsHeaders(origin){return{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Accept,X-Admin-Key,X-NetShop-Signature,X-Webhook-Signature,X-Signature,X-NetShop-Timestamp,X-Webhook-Timestamp','Access-Control-Max-Age':'86400','Vary':'Origin'}}
function json(data,status=200,origin='*'){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...corsHeaders(origin)}})}
function normalizePhone(v){const d=String(v||'').replace(/\D/g,'');if(d.startsWith('258'))return'+'+d;if(d.startsWith('0'))return'+258'+d.slice(1);return'+258'+d}
function uuid(){return crypto.randomUUID()}
function timingSafeEqual(a,b){if(a.length!==b.length)return false;let r=0;for(let i=0;i<a.length;i++)r|=a.charCodeAt(i)^b.charCodeAt(i);return r===0}
function hex(buffer){return[...new Uint8Array(buffer)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function verifyWebhook(request,body,secret){if(!secret)return false;const sig=request.headers.get('X-NetShop-Signature')||request.headers.get('X-Webhook-Signature')||request.headers.get('X-Signature');if(!sig)return false;const ts=request.headers.get('X-NetShop-Timestamp')||request.headers.get('X-Webhook-Timestamp');if(ts){const n=Number(ts);if(!Number.isFinite(n))return false;const ms=n<1e12?n*1000:n;if(Math.abs(Date.now()-ms)>300000)return false}const enc=new TextEncoder();const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const normalized=sig.replace(/^sha256=/i,'').trim().toLowerCase();for(const value of ts?[body,`${ts}.${body}`]:[body]){const digest=hex(await crypto.subtle.sign('HMAC',key,enc.encode(value)));if(timingSafeEqual(digest,normalized))return true}return false}

async function getOrder(env,id){return await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(id).first()}
async function listOrders(env){return(await env.DB.prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 500').all()).results||[]}
async function saveOrder(env,o){await env.DB.prepare(`INSERT INTO orders (id,game,pack,amount,currency,player_id,contact,payment_method,payment_id,payment_reference,status,payment_status,delivery_status,error,created_at,updated_at,paid_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
ON CONFLICT(id) DO UPDATE SET game=excluded.game,pack=excluded.pack,amount=excluded.amount,currency=excluded.currency,player_id=excluded.player_id,contact=excluded.contact,payment_method=excluded.payment_method,payment_id=excluded.payment_id,payment_reference=excluded.payment_reference,status=excluded.status,payment_status=excluded.payment_status,delivery_status=excluded.delivery_status,error=excluded.error,updated_at=excluded.updated_at,paid_at=excluded.paid_at`).bind(o.id,o.game,o.pack,o.amount,o.currency,o.playerId,o.contact,o.payment,o.paymentId,o.paymentReference,o.status,o.paymentStatus,o.deliveryStatus,o.error||null,o.createdAt,o.updatedAt||null,o.paidAt||null).run()}
function applyPaymentStatus(o,status){const s=String(status||'').toLowerCase();o.paymentStatus=s||o.paymentStatus;o.updatedAt=new Date().toISOString();if(s.includes('succeed')||s==='successful'||s==='paid'||s==='completed'||s==='payment.succeeded'){o.status='Pagamento confirmado';o.deliveryStatus='ready_for_delivery';o.paidAt=o.paidAt||new Date().toISOString()}else if(s.includes('fail')||s.includes('cancel')||s==='payment.failed'||s==='expired'){o.status='Pagamento falhou';o.deliveryStatus='cancelled'}else if(s.includes('pending')||s==='processing'||s==='requires_action'){o.status='Pagamento pendente';o.deliveryStatus='waiting_payment'}return o}
function adminAuthorized(request,env){return Boolean(env.ADMIN_KEY)&&request.headers.get('X-Admin-Key')===env.ADMIN_KEY}

export default{async fetch(request,env){const origin=env.ALLOWED_ORIGIN||'*';const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...corsHeaders(origin),'Content-Length':'0'}});
if(request.method==='GET'&&(url.pathname==='/'||url.pathname==='/health'))return json({ok:true,service:'GameRecarga MZ API',configured:Boolean(env.NETSHOP_API_KEY),webhookConfigured:Boolean(env.NETSHOP_WEBHOOK_SECRET),storageConfigured:Boolean(env.DB),adminConfigured:Boolean(env.ADMIN_KEY)},200,origin);

if(request.method==='POST'&&url.pathname==='/webhook'){const raw=await request.text();if(!await verifyWebhook(request,raw,env.NETSHOP_WEBHOOK_SECRET))return json({error:'invalid_webhook_signature'},401,origin);let event;try{event=JSON.parse(raw)}catch{return json({error:'invalid_json'},400,origin)}const data=event?.data||event?.charge||event?.payment||event;const reference=data?.reference||data?.payment_reference||data?.charge?.reference||data?.payment?.reference;const chargeId=data?.id||data?.charge_id||data?.charge?.id;const status=data?.status||data?.charge?.status||data?.payment?.status||event?.type||event?.event;const found=(await listOrders(env)).find(o=>(reference&&(o.payment_reference===reference||o.id===reference))||(chargeId&&o.payment_id===chargeId));if(!found)return json({ok:true,received:true,matched:false,reference,status},200,origin);const o={id:found.id,game:found.game,pack:found.pack,amount:found.amount,currency:found.currency,playerId:found.player_id,contact:found.contact,payment:found.payment_method,paymentId:found.payment_id,paymentReference:found.payment_reference,status:found.status,paymentStatus:found.payment_status,deliveryStatus:found.delivery_status,createdAt:found.created_at,updatedAt:found.updated_at,paidAt:found.paid_at};applyPaymentStatus(o,status);await saveOrder(env,o);await env.DB.prepare('INSERT INTO payments (id,order_id,provider,provider_payment_id,reference,status,amount,currency,raw_event,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,raw_event=excluded.raw_event,updated_at=excluded.updated_at').bind(uuid(),o.id,'NetShop',chargeId||null,reference||null,o.paymentStatus,o.amount,o.currency,raw,new Date().toISOString(),o.updatedAt).run();return json({ok:true,received:true,matched:true,orderId:o.id,status:o.status},200,origin)}

if(request.method==='GET'&&url.pathname.startsWith('/orders/')){const id=decodeURIComponent(url.pathname.slice('/orders/'.length));if(!id)return json({error:'missing_order_id'},400,origin);const o=await getOrder(env,id);if(!o)return json({error:'not_found'},404,origin);return json({id:o.id,game:o.game,pack:o.pack,amount:o.amount,currency:o.currency,playerId:o.player_id,payment:o.payment_method,paymentReference:o.payment_reference,status:o.status,paymentStatus:o.payment_status,deliveryStatus:o.delivery_status,createdAt:o.created_at,updatedAt:o.updated_at,paidAt:o.paid_at,error:o.error},200,origin)}

if(request.method==='GET'&&url.pathname==='/admin/orders'){if(!adminAuthorized(request,env))return json({error:'unauthorized'},401,origin);return json(await listOrders(env),200,origin)}
if(request.method==='GET'&&url.pathname==='/admin/dashboard'){if(!adminAuthorized(request,env))return json({error:'unauthorized'},401,origin);const rows=await listOrders(env);const paid=rows.filter(o=>o.status==='Pagamento confirmado'||['successful','succeeded','paid','completed'].includes(String(o.payment_status).toLowerCase()));return json({orders:rows.length,paid:paid.length,revenue:paid.reduce((s,o)=>s+Number(o.amount||0),0),pending:rows.filter(o=>o.status==='Pagamento pendente').length,failed:rows.filter(o=>o.status==='Pagamento falhou').length},200,origin)}

if(!env.NETSHOP_API_KEY)return json({error:'server_not_configured'},500,origin);
if(request.method==='POST'&&url.pathname==='/create-order'){let body;try{body=await request.json()}catch{return json({error:'invalid_json'},400,origin)}const{amount,currency='MZN',method,msisdn,reference,game,pack,playerId}=body;const amountNumber=Number(amount);if(!Number.isFinite(amountNumber)||amountNumber<10||amountNumber>50000)return json({error:'invalid_amount'},400,origin);if(!WALLET_IDS[method])return json({error:'invalid_method'},400,origin);if(!msisdn||!reference||!game||!pack||!playerId)return json({error:'missing_fields'},400,origin);const order={id:String(reference),game:String(game),pack:String(pack),amount:amountNumber,currency,playerId:String(playerId),contact:String(msisdn),payment:String(method),status:'Pagamento pendente',paymentStatus:'pending',deliveryStatus:'waiting_payment',createdAt:new Date().toISOString()};await saveOrder(env,order);const payload={amount:amountNumber,currency,method,msisdn:normalizePhone(msisdn),reference:order.id,description:`${order.game} - ${order.pack}`.slice(0,180)};const response=await fetch(`${NETSHOP_BASE}/charges`,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json',Authorization:`Bearer ${env.NETSHOP_API_KEY}`,'X-API-Version':'2024-10-12','X-Wallet-ID':WALLET_IDS[method],'Idempotency-Key':order.id},body:JSON.stringify(payload)});const text=await response.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}}const result=data?.data||data;if(!response.ok){order.status='Pagamento falhou';order.paymentStatus='error';order.error=result?.message||result?.error?.message||result?.error||text||`NetShop HTTP ${response.status}`;order.updatedAt=new Date().toISOString();await saveOrder(env,order);return json({ok:false,status:response.status,data,orderId:order.id},502,origin)}order.paymentId=result?.id||result?.charge_id||null;order.paymentReference=result?.reference||result?.payment_reference||order.id;order.checkoutUrl=result?.checkout_url||result?.payment_url||result?.checkoutUrl||null;applyPaymentStatus(order,result?.status||'pending');await saveOrder(env,order);return json({ok:true,orderId:order.id,id:order.id,status:order.status,paymentStatus:order.paymentStatus,paymentReference:order.paymentReference,checkoutUrl:order.checkoutUrl,chargeId:order.paymentId},200,origin)}
return json({error:'not_found',method:request.method,path:url.pathname},404,origin)}};
