name = "gamerecarga-mz-api"
main = "cloudflare-worker.js"
compatibility_date = "2026-09-06"

[vars]
ALLOWED_ORIGIN = "https://valterpedrojorge01-pixel.github.io"

[secrets]
required = ["NETSHOP_API_KEY", "NETSHOP_WEBHOOK_SECRET", "ADMIN_KEY"]

[[d1_databases]]
binding = "DB"
database_name = "gamerecarga-mz-db"
database_id = "1ff76b25-9aeb-437e-b705-e109ac56e73e"
migrations_dir = "migrations"
